### ISSUE TITLE
v11 Proto Checklist Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/PicoBuck#1]
If the board's size or form is causing or the reason for any of the issues mentioned below, and said issue cannot be resolved without disrupting the size or form; just mention that. I understand that the size/form of this board is an important selling point.

ISSUES:
(1) There are a couple 4-way junctions off of each of the AL8805's

(2) Version number in SCH and board are v10, should be v11

(3) VIN range not clearly labelled in SCH

(4) AL8805 needs value

(5) Got some weird angles on a lot of traces, it looks like there could have been a slight movement of a group of parts.

(6) Need measures

(7) Looks like the CC attribute in the BRD is there, but it is on Tvalues

(8) The "Revised by", and the designer and reviser names are absent in the BRD

(9) Looks like the bottom screw terminals have "CHx" as the name instead of the value. I'm assuming this refers to the output channel. Need a JP in the name field for those.

QUESTIONABLE ISSUES:
(10) Sparkfun logo is missing in the SCH, I wasn't sure if this was intentional because it's a collaboration.

that's it.

**Comment by mhord** [comment]
You're on the wrong branch, man. Pretty much all of that stuff is fixed.

The branch in question is "hi_pow".

**Comment by ericorosel** [comment]
That's weird, in the bug it says to check out the V_11 branch, which is what I looked at and is where I originally filed this.

It appears that there is no longer a V_11 Branch of the repo on the Github page. However my local still shows a V_11 branch for this REPO, and the files in which I generated the issues from still show those issues.

Did the V_11 branch get removed?

**Comment by ericorosel** [comment]
![screen_shot_1](https://cloud.githubusercontent.com/assets/3160317/8727584/beddd59c-2b9d-11e5-9103-22e61e709677.png)

**Comment by mhord** [comment]
I deleted V_11 and replaced it with hi_pow.

I realized that naming it V_11 was premature, as there may be additional versions past 11 if it takes more than one proto round.
